// <autogenerated/>
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("EnterpriseEngineTest")]
[assembly: AssemblyDescription("EnterpriseEngine")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("EnterpriseEngine")]
[assembly: AssemblyProduct("EnterpriseEngine")]
[assembly: AssemblyCopyright("Copyright © EnterpriseEngine 2013")]
[assembly: AssemblyTrademark("EnterpriseEngine")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: Guid("9d5d1631-a9d3-4ec4-b2e3-f3521396c435")]
[assembly: AssemblyFileVersion("1.0.1.0")]
[assembly: AssemblyVersionAttribute("1.0.1.0")]
