// <autogenerated/>
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("SqliteLogging")]
[assembly: AssemblyDescription("EnterpriseEngine Logging")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("EnterpriseEngine")]
[assembly: AssemblyProduct("SqliteLogging")]
[assembly: AssemblyCopyright("Copyright © EnterpriseEngine 2013")]
[assembly: AssemblyTrademark("EnterpriseEngine")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: Guid("cde35dc4-99d6-4b0d-92d6-8132da14187c")]
[assembly: AssemblyVersion("1.0.1.0")]
[assembly: AssemblyFileVersion("1.0.1.0")]
